/**
 * 수강신청 관련 에러 코드
 */
export const enrollmentErrorCodes = {
  // 일반 에러
  ENROLLMENT_NOT_FOUND: 'ENROLLMENT_NOT_FOUND',
  INVALID_COURSE_ID: 'INVALID_COURSE_ID',
  INVALID_USER_ID: 'INVALID_USER_ID',
  
  // 권한 에러
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  
  // 비즈니스 규칙 에러
  COURSE_NOT_PUBLISHED: 'COURSE_NOT_PUBLISHED',
  ALREADY_ENROLLED: 'ALREADY_ENROLLED',
  NOT_ENROLLED: 'NOT_ENROLLED',
  COURSE_ARCHIVED: 'COURSE_ARCHIVED',
  
  // 데이터베이스 에러
  ENROLLMENT_CREATION_ERROR: 'ENROLLMENT_CREATION_ERROR',
  ENROLLMENT_UPDATE_ERROR: 'ENROLLMENT_UPDATE_ERROR',
  ENROLLMENT_DELETE_ERROR: 'ENROLLMENT_DELETE_ERROR',
  ENROLLMENT_FETCH_ERROR: 'ENROLLMENT_FETCH_ERROR',
  
  // 검증 에러
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;



