/**
 * 과제 관리 기능의 에러 코드 정의
 */

export const assignmentErrorCodes = {
  // 과제 생성/수정/삭제
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
  ASSIGNMENT_WEIGHT_EXCEEDED: 'ASSIGNMENT_WEIGHT_EXCEEDED',
  ASSIGNMENT_PAST_DEADLINE: 'ASSIGNMENT_PAST_DEADLINE',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  INVALID_INPUT: 'INVALID_INPUT',

  // 제출물 관리
  SUBMISSION_NOT_FOUND: 'SUBMISSION_NOT_FOUND',
  SUBMISSION_ALREADY_GRADED: 'SUBMISSION_ALREADY_GRADED',
  INVALID_SCORE: 'INVALID_SCORE',

  // 데이터베이스 에러
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type AssignmentErrorCode = (typeof assignmentErrorCodes)[keyof typeof assignmentErrorCodes];

