export const assignmentErrorCodes = {
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
  ASSIGNMENT_CREATION_ERROR: 'ASSIGNMENT_CREATION_ERROR',
  ASSIGNMENT_UPDATE_ERROR: 'ASSIGNMENT_UPDATE_ERROR',
  ASSIGNMENT_DELETE_ERROR: 'ASSIGNMENT_DELETE_ERROR',
  SUBMISSION_NOT_FOUND: 'SUBMISSION_NOT_FOUND',
  SUBMISSION_ALREADY_EXISTS: 'SUBMISSION_ALREADY_EXISTS',
  SUBMISSION_CREATE_ERROR: 'SUBMISSION_CREATE_ERROR',
  SUBMISSION_UPDATE_ERROR: 'SUBMISSION_UPDATE_ERROR',
  ASSIGNMENT_STATUS_CHANGE_ERROR: 'ASSIGNMENT_STATUS_CHANGE_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_INSTRUCTOR: 'NOT_INSTRUCTOR',
  NOT_LEARNER: 'NOT_LEARNER',
} as const;

export type AssignmentErrorCode = keyof typeof assignmentErrorCodes;

export type AssignmentServiceError = {
  code: typeof assignmentErrorCodes[AssignmentErrorCode];
  message: string;
};
