// Error codes for operator functionality
export const operatorErrorCodes = {
  // 신고 관련
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  INVALID_REPORT_STATUS_TRANSITION: 'INVALID_REPORT_STATUS_TRANSITION',
  INVALID_ADMIN_ACTION: 'INVALID_ADMIN_ACTION',
  OPERATOR_PERMISSION_DENIED: 'OPERATOR_PERMISSION_DENIED',
  REPORTS_FETCH_ERROR: 'REPORTS_FETCH_ERROR',
  REPORT_FETCH_ERROR: 'REPORT_FETCH_ERROR',
  REPORT_STATUS_UPDATE_ERROR: 'REPORT_STATUS_UPDATE_ERROR',
  REPORT_ACTION_ERROR: 'REPORT_ACTION_ERROR',
  
  // 메타데이터 관련
  METADATA_IN_USE: 'METADATA_IN_USE',
  METADATA_FETCH_ERROR: 'METADATA_FETCH_ERROR',
  METADATA_CREATION_ERROR: 'METADATA_CREATION_ERROR',
  METADATA_UPDATE_ERROR: 'METADATA_UPDATE_ERROR',
  METADATA_DEACTIVATION_ERROR: 'METADATA_DEACTIVATION_ERROR',
  METADATA_CHECK_ERROR: 'METADATA_CHECK_ERROR',
  METADATA_DUPLICATE: 'METADATA_DUPLICATE',
  METADATA_NOT_FOUND: 'METADATA_NOT_FOUND',
} as const;

export type OperatorErrorCode = (typeof operatorErrorCodes)[keyof typeof operatorErrorCodes];