// Error codes for operator functionality
export const operatorErrorCodes = {
  // Report errors
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORTS_FETCH_ERROR: 'REPORTS_FETCH_ERROR',
  REPORT_FETCH_ERROR: 'REPORT_FETCH_ERROR',
  REPORT_STATUS_UPDATE_ERROR: 'REPORT_STATUS_UPDATE_ERROR',
  REPORT_ACTION_ERROR: 'REPORT_ACTION_ERROR',
  INVALID_REPORT_STATUS_TRANSITION: 'INVALID_REPORT_STATUS_TRANSITION',

  // Metadata errors
  METADATA_NOT_FOUND: 'METADATA_NOT_FOUND',
  METADATA_FETCH_ERROR: 'METADATA_FETCH_ERROR',
  METADATA_CREATION_ERROR: 'METADATA_CREATION_ERROR',
  METADATA_UPDATE_ERROR: 'METADATA_UPDATE_ERROR',
  METADATA_DEACTIVATION_ERROR: 'METADATA_DEACTIVATION_ERROR',
  METADATA_CHECK_ERROR: 'METADATA_CHECK_ERROR',
  METADATA_DUPLICATE: 'METADATA_DUPLICATE',
  METADATA_IN_USE: 'METADATA_IN_USE',

  // Admin action errors
  INVALID_ADMIN_ACTION: 'INVALID_ADMIN_ACTION',
  OPERATOR_PERMISSION_DENIED: 'OPERATOR_PERMISSION_DENIED',
} as const;

export type OperatorErrorCode = keyof typeof operatorErrorCodes;