export const courseErrorCodes = {
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  COURSE_TITLE_DUPLICATE: 'COURSE_TITLE_DUPLICATE',
  COURSE_CREATION_ERROR: 'COURSE_CREATION_ERROR',
  COURSE_UPDATE_ERROR: 'COURSE_UPDATE_ERROR',
  COURSE_STATUS_CHANGE_ERROR: 'COURSE_STATUS_CHANGE_ERROR',
  COURSE_DELETE_ERROR: 'COURSE_DELETE_ERROR',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  COURSE_HAS_ENROLLMENTS: 'COURSE_HAS_ENROLLMENTS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_INSTRUCTOR: 'NOT_INSTRUCTOR',
} as const;
