export const gradeErrorCodes = {
  GRADES_FETCH_ERROR: 'GRADES_FETCH_ERROR',
  GRADES_VALIDATION_ERROR: 'GRADES_VALIDATION_ERROR',
  GRADES_NOT_FOUND: 'GRADES_NOT_FOUND',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SUBMISSION_NOT_FOUND: 'SUBMISSION_NOT_FOUND',
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
  INVALID_SCORE_RANGE: 'INVALID_SCORE_RANGE',
  MISSING_FEEDBACK: 'MISSING_FEEDBACK',
  SUBMISSION_ALREADY_GRADED: 'SUBMISSION_ALREADY_GRADED'
} as const;

export type GradeErrorCode = keyof typeof gradeErrorCodes;

export type GradeServiceError = {
  code: typeof gradeErrorCodes[GradeErrorCode];
  message: string;
};